### ISSUE TITLE
java.lang.IllegalArgumentException: UT010023: Request org.openspcoop2.pdd.services.connector.FormUrlEncodedHttpServletRequest@493922c6 was not original or a wrapper

### ISSUE THREAD

**Issue by marcomarsala** [link-it/GovWay#11]
Sto tentando di inviare la fattura elettronica [IT01629370097_00001.xml.p7m.zip](https://github.com/link-it/GovWay/files/2598784/IT01629370097_00001.xml.p7m.zip)  (il file è qui allegato in formato .ZIP perche GitHub non lo accetta, ma l'invio è effettuato con il file .xml.p7m non compresso) al SDI (modalità test) utilizzando il comando:

`curl -X POST -d IT01629370097_00001.xml.p7m "https://fe.thenetworksolution.it/govway/sdi/out/xml2soap/Nineproof/CentroServiziFatturaPA/SdIRiceviFile/1?Versione=FPA12&TipoFile=P7M&IdPaese=IT&IdCodice=01629370097"`

ma ricevo in output il seguente errore:

```
Error processing request
Context Path:/govway
Servlet Path:
Path Info:/sdi/out/xml2soap/Nineproof/CentroServiziFatturaPA/SdIRiceviFile/1
Query String:Versione=FPA12&TipoFile=P7M&IdPaese=IT&IdCodice=01629370097
Stack Trace:
java.lang.IllegalArgumentException: UT010023: Request org.openspcoop2.pdd.services.connector.FormUrlEncodedHttpServletRequest@493922c6 was not original or a wrapper
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:116)
	at org.openspcoop2.pdd.services.connector.FormUrlEncodedFilter.doFilter(FormUrlEncodedFilter.java:58)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by marcomarsala** [comment]
Ho aggiunto il parametro `allow-non-standard-wrappers="true"` al file di configurazione `/opt/wildfly/standalone/configuration/standalone.xml` come indicato cercando sul web, è corretto?

Dopo averlo fatto l'errore scompare e l'output diventa semplicemente:

`<html><head><title>Error</title></head><body>OpenSPCoop2-OP20000-0001</body></html>`

**Comment by andreapoli** [comment]
No non è corretto. Ripristina la precedente configurazione.
Il problema è dovuto al fatto che non fornisci il corretto header http Content-Type.

Per inviare una fattura devi utilizzare il seguente comando curl:

curl -X POST -basic --user SdIRiceviFile:123456 --data-binary @IT01629370097_00001.xml.p7m -H "Content-Type: application/pkcs7-mime" "https://fe.thenetworksolution.it/govway/sdi/out/xml2soap/Nineproof/CentroServiziFatturaPA/SdIRiceviFile/v1?Versione=FPA12&TipoFile=P7M&IdPaese=IT&IdCodice=01629370097"

NOTA:  utilizza l'opzione "--data-binary" invece che '-d' per far si' che il curl non modifichi in alcun modo la fattura originale.

Ho aggiornato la [documentazione](https://github.com/link-it/GovWay/blob/master/resources/doc/pdf/GovWay-ManualeUtente.pdf) in modo da fornire esempi di comandi curl che permettono di comprendere meglio come invocare GovWay per spedire fatture. Vedi la sezione "5.2.1 Invio della fattura".

**Comment by marcomarsala** [comment]
Utilizzando il tuo comando, dopo avere incrementato la memoria del metaspace nella configurazione dell’Application server, questo errore scompare.

**Comment by marcomarsala** [comment]
Su Windows bisogna anche aggiungere il certificato della CA Entrate all'archivio dei certificati di curl (non lo prende dal sistema operativo), altrimenti quel comando ritornerà l'errore "curl: (60) SSL certificate problem: unable to get local issuer certificate".

Oppure aggiungere l'opzione `-k` alla linea di comando per consentire connessioni insicure,
