### ISSUE TITLE
Installazione GovWay 3.3.12 - distribuzione binaria su WildFly 26

### ISSUE THREAD

**Issue by hal-berto** [link-it/govway#132]
Buongiorno,
sto provando ad installare la versione in oggetto di GovWay seguendo le indicazioni riportate nella documentazione.
L'AS che sto utilizzando è:
-WildFly Preview 26.0.0.Final (WildFly Core 18.0.0.Final)
Come database utilizzo invece MySQL

Una volta completata la procedura di installazione e copiati i file war, ear e di configurazione nelle cartelle indicate nella procedura, all'avvio di wildfly vengono loggati parecchi errori o warinig che sembrano ricondurre a classi non trovate (o presenti nei war ma duplicate). Ne riporto qui sotto alcuni, oltre ad allegare il file di log:

2023-06-14 12:32:05,245 INFO  [org.wildfly.security] (ServerService Thread Pool -- 27) ELY00001: WildFly Elytron version 1.18.1.Final
2023-06-14 12:33:03,519 ERROR [stderr] (ServerService Thread Pool -- 6) [ServerService Thread Pool -- 6] ERROR Transformer - Transform failure:
2023-06-14 12:33:03,521 ERROR [stderr] (ServerService Thread Pool -- 6) org.eclipse.transformer.TransformException: Failure while processing [ constants/package-info.class ] from [ lib/openspcoop2_core-3.3.12.jar ]
....
2023-06-14 12:33:03,695 ERROR [stderr] (ServerService Thread Pool -- 6) Caused by: java.util.zip.ZipException: duplicate entry: constants/package-info.class
2023-06-14 12:33:03,698 ERROR [stderr] (ServerService Thread Pool -- 6) 	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
2023-06-14 12:33:03,699 ERROR [stderr] (ServerService Thread Pool -- 6) 	at org.wildfly.deployment.transformation//org.eclipse.transformer.action.impl.ContainerActionImpl.apply(ContainerActionImpl.java:282)
2023-06-14 12:33:03,700 ERROR [stderr] (ServerService Thread Pool -- 6) 	... 25 more

[----------------------------------------------]

2023-06-14 12:34:45,001 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."govwayMonitor.war".undertow-deployment.UndertowDeploymentInfoService: org.jboss.msc.service.StartException in service jboss.deployment.unit."govwayMonitor.war".undertow-deployment.UndertowDeploymentInfoService: Failed to start service
.....
Caused by: java.lang.NoClassDefFoundError: Failed to link javax/faces/webapp/FacesServlet (Module "deployment.govwayMonitor.war" from Service Module Loader): javax/servlet/Servlet

[----------------------------------------------]

2023-06-14 12:34:37,370 WARN  [org.jboss.modules.define] (MSC service thread 1-2) Failed to define class org.openspcoop2.web.ctrlstat.servlet.config.ConfigurazioneSistemaExporter in Module "deployment.govwayConsole.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link org/openspcoop2/web/ctrlstat/servlet/config/ConfigurazioneSistemaExporter (Module "deployment.govwayConsole.war" from Service Module Loader): javax/servlet/http/HttpServlet

A cosa possono essere dovuti questi errori? C'è qualcosa che non va bene con l'AS che sto utilizzando?
Grazie

[server.zip](https://github.com/link-it/govway/files/11744838/server.zip)

**Comment by andreapoli** [comment]
Buongiorno @hal-berto ,
 non deve essere utilizzata la versione "WildFly Preview" ma la versione "EE 8 Full & Web Distribution".
 
Ad esempio: https://github.com/wildfly/wildfly/releases/download/26.1.3.Final/wildfly-26.1.3.Final.tar.gz

**Comment by andreapoli** [comment]
@hal-berto ti ringrazio per la segnalazione, in effetti si tratta di un bug che blocca l'avvio poichè i PosixFilePermission non sono supportati su windows.

Potresti aprire un bug dedicato alla problematica riscontrata ?
